apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  destination:
    namespace: spark-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: spark-operator
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: 1.4.3
    helm:
      releaseName: spark-operator
      valuesObject:
        webhook:
          enable: true
        sparkJobNamespaces: 
          - spark
        serviceAccounts:
          spark:
            create: true
            name: spark
          sparkoperator:
            create: true
            name: spark-operator
        rbac:
          createClusterRole: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
