apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  project: default
  source:
    path: tools/k8s/local
    repoURL: https://github.com/Thelin90/datapains-prometheus-k8s
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
